### ISSUE TITLE
Cannot close the CardAndTerminalManager while using the BeIDCards implementation

### ISSUE THREAD

**Issue by florian-courault** [Fedict/commons-eid#9]
Hello, 
I noticed a bug using the BeIDCards class: When its "close" method is called, nothing happens: 
It calls the "stop" method of its BeIDCardManager, which does nothing, because the class uses its own object "CardAndTerminalManager". So, this one is never closed. 
I proposed a pull request that fixes this bug, [here](https://github.com/Fedict/commons-eid/pull/8/commits/68bdfa12db4977e8db35fbef481efcf521438d76).

Thank you for your attention and for your very useful software :) !

**Comment by janvdbergh** [comment]
Thanks for your pull request. I will look into it tomorrow.

**Comment by janvdbergh** [comment]
Hi. I have merged your pull request and am now trying to do a release to maven.eid.belgium.be. (There are currently some issues with this maven repository, but you can already checkout tag commons-eid-parent-1.0.2 and build it yourself.)
Thanks again for your contribution.

**Comment by florian-courault** [comment]
Thanks for your responsiveness and help !

**Comment by florian-courault** [comment]
Hello again, I would like to use your maven repository directly, but I cannot access it. Do you have any information about this?

**Comment by janvdbergh** [comment]
Hi, Florian. Apparently the Maven repository does not exist anymore. We are looking into a different solution (e.g. hosting the artifacts on Maven Central).
For now, the only solution is to build the code yourself.
